# Generated by Django 4.2.9 on 2025-02-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pofitprice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
