# Generated by Django 4.2.9 on 2025-02-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_salerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='salerecord',
            name='Pofitprice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
