# Generated by Django 4.2.9 on 2025-03-18 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_salerecord_cashier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salerecord',
            options={'verbose_name': 'รายการสินค้าที่บันทึก', 'verbose_name_plural': 'บันทึกรายการสำหรับการขาย'},
        ),
    ]
