# Generated by Django 5.1.4 on 2025-01-04 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product1',
            name='description',
        ),
    ]
