# Generated by Django 5.1.4 on 2025-01-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0002_remove_product1_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product1',
            name='description',
            field=models.TextField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
