# Generated by Django 5.1.4 on 2025-01-04 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0003_product1_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productapp.category'),
        ),
    ]
