# Generated by Django 5.1.4 on 2025-01-04 20:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0004_alter_product1_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product1',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product1',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
