# Generated by Django 5.1.4 on 2025-01-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0008_product1_profitprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product1',
            name='stock',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
