# Generated by Django 5.1.4 on 2025-01-22 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0009_alter_product1_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product1',
            name='barcode',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
