# Generated by Django 4.2.9 on 2025-03-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0011_alter_product1_category_alter_product1_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='frolink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'frolink',
                'verbose_name_plural': 'กลับไปหน้า DashBord',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'ประเภทรายการสินค้า'},
        ),
        migrations.AlterModelOptions(
            name='product1',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'รายการสินค้า'},
        ),
    ]
