# Generated by Django 4.2.9 on 2025-03-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0012_frolink_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product1',
            name='barcode',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
